version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  unit-test-latest:
    docker:
      - image: golang:stretch
    steps:
      - checkout
      - run:
          name: Build project and perform tests
          command: make test
  unit-test:
      docker:
        - image: circleci/golang:1.13
      steps:
        - checkout
        - run:
            name: Build project and perform tests
            command: make test
        - codecov/upload:
            file: ./single.coverprofile

workflows:
  version: 2
  test:
    jobs:
      - unit-test
      - unit-test-latest