version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  unit-test-rust:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - run:
          name: Run all tests
          command: cargo test --all
  unit-test-latest-go:
    docker:
      - image: golang:stretch
    steps:
      - checkout
      - run:
          name: Build project and perform tests
          command: make test
  unit-test-go:
      docker:
        - image: circleci/golang:1.13
      steps:
        - checkout
        - run:
            name: Build project and perform tests
            command: make test
        - codecov/upload:
            file: ./single.coverprofile

workflows:
  version: 2
  test:
    jobs:
      - unit-test-go
      - unit-test-latest-go
      - unit-test-rust